ktor {
  deployment {
    port = 8081
    port = ${?PORT}
    watch = [ classes ]
  }

  application {
    modules = [ com.example.stocktracker.mobileapi.bootstrap.ApplicationModuleKt.module ]
  }
}

app {
  env = ${?APP_ENV}
  serviceName = "mobile-api"

  logging {
    level = ${?LOG_LEVEL}
  }

  observability {
    tracingEnabled = true
    serviceName = "mobile-api"
    otlpEndpoint = ${?OTEL_EXPORTER_OTLP_ENDPOINT}
  }

  upstream {
    portfolioBaseUrl = ${?PORTFOLIO_SERVICE_BASE_URL}
    quotesBaseUrl = ${?QUOTES_SERVICE_BASE_URL}
    timeoutMs = 2000
  }
}
