ktor {
  deployment {
    port = 8080
    watch = [ classes ]
  }

  application {
    modules = [ com.example.stocktracker.bootstrap.ApplicationModuleKt.module ]
  }
}

app {
  env = ${?APP_ENV}

  logging {
    level = ${?LOG_LEVEL}
  }

  database {
    jdbcUrl = ${?DATABASE_URL}
    driverClassName = "org.postgresql.Driver"
    maxPoolSize = 10
    autoCommit = false
    connectionTimeoutMs = 30000
    validationTimeoutMs = 5000
  }
}
